SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

CREATE PROC [dbo].[sp_CRMProcess_UpdateGUIDs_ProdCopy_Contact]
AS

UPDATE A
SET SSB_CRMSYSTEM_ACCT_ID__c = b.SSB_CRMSYSTEM_ACCT_ID__C,
	SSB_CRMSYSTEM_CONTACT_ID__c = b.SSB_CRMSYSTEM_CONTACT_ID__c
FROM ProdCopy.Contact A
INNER JOIN [dbo].[vwCRMProcess_UpdateGUIDs_ProdCopyContact] b
	 ON b.id = a.id
--WHERE a.SSB_CRMSYSTEM_CONTACT_ID__c IS NULL OR a.SSB_CRMSYSTEM_CONTACT_ID__c <> b.[SSB_CRMSYSTEM_CONTACT_ID]
GO
