CREATE TABLE [dbo].[AUDIT_Contact_Custom_Changes]
(
[Id] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_SSID_Winner__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_SSB_CRMSYSTEM_SSID_Winner__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_FullArchitcs_IDs__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_SSB_CRMSYSTEM_FullArchitcs_IDs__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSB_CRMSYSTEM_DimCustomerIDs__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_SSB_CRMSYSTEM_DimCustomerIDs__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Archtics_ID__c] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Archtics_ID__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MobilePhone] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_MobilePhone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Email] [nvarchar] (80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OtherPhone] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_OtherPhone] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Age__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Age__c] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birthday__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Birthday__c] [nvarchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Email_Activity_Last_15_Days__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[current_Email_Activity_Last_15_Days__c] [bit] NULL,
[Gender__c] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Gender__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kings_com_Web_View_Last_15_Days__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[current_Kings_com_Web_View_Last_15_Days__c] [bit] NULL,
[Marital_Status__c] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Marital_Status__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Occupation__c] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Occupation__c] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PersonicX_Cluster__c] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_PersonicX_Cluster__c] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Fax] [nvarchar] (40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH_Account__c] [bit] NULL,
[current_STH_Account__c] [bit] NULL,
[Num_of_games_bought_Current_Season__c] [int] NULL,
[current_Num_of_games_bought_Current_Season__c] [float] NULL,
[Num_of_games_attended_Current_Season__c] [int] NULL,
[current_Num_of_games_attended_Current_Season__c] [float] NULL,
[Attendance_Rate_Current_Season__c] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Attendance_Rate_Current_Season__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Total_Kings_Tix_revenue_Current_Season__c] [decimal] (16, 2) NULL,
[current_Total_Kings_Tix_revenue_Current_Season__c] [float] NULL,
[Total_Kings_Tix_Rev_Previous_Season__c] [decimal] (16, 2) NULL,
[current_Total_Kings_Tix_Rev_Previous_Season__c] [float] NULL,
[Num_arena_events_bought_Current_Season__c] [int] NULL,
[current_Num_arena_events_bought_Current_Season__c] [float] NULL,
[Total_arena_event_Tix_Rev_Current_Season__c] [decimal] (16, 2) NULL,
[current_Total_arena_event_Tix_Rev_Current_Season__c] [float] NULL,
[Season_Ticket_Spend_Current_Season__c] [decimal] (16, 2) NULL,
[current_Season_Ticket_Spend_Current_Season__c] [float] NULL,
[Num_of_games_forwarded_Current_Season__c] [int] NULL,
[current_Num_of_games_forwarded_Current_Season__c] [float] NULL,
[Num_of_games_posted_Current_Season__c] [int] NULL,
[current_Num_of_games_posted_Current_Season__c] [float] NULL,
[Num_of_games_resold_Current_Season__c] [int] NULL,
[current_Num_of_games_resold_Current_Season__c] [float] NULL,
[Num_seats_forwarded_Current_Season__c] [int] NULL,
[current_Num_seats_forwarded_Current_Season__c] [float] NULL,
[Num_seats_posted_Current_Season__c] [int] NULL,
[current_Num_seats_posted_Current_Season__c] [float] NULL,
[Num_seats_resold_Current_Season__c] [int] NULL,
[current_Num_seats_resold_Current_Season__c] [float] NULL,
[Num_games_received_via_Fwd_Current__c] [int] NULL,
[current_Num_games_received_via_Fwd_Current__c] [float] NULL,
[Tot_Rev_seats_bought_resale_TM_Plus_CS__c] [decimal] (16, 2) NULL,
[current_Tot_Rev_seats_bought_resale_TM_Plus_CS__c] [float] NULL,
[Tot_rev_seats_bought_resale_TM_Plus_PS__c] [decimal] (16, 2) NULL,
[current_Tot_rev_seats_bought_resale_TM_Plus_PS__c] [float] NULL,
[Attendance_Rate_Previous_Season__c] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Attendance_Rate_Previous_Season__c] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Num_of_games_attended_Previous_Season__c] [int] NULL,
[current_Num_of_games_attended_Previous_Season__c] [float] NULL,
[Num_of_games_bought_Previous_Season__c] [int] NULL,
[current_Num_of_games_bought_Previous_Season__c] [float] NULL,
[Num_arena_events_bought_Previous_Season__c] [int] NULL,
[current_Num_arena_events_bought_Previous_Season__c] [float] NULL,
[Total_arena_event_Tix_Rev_Previous__c] [decimal] (16, 2) NULL,
[current_Total_arena_event_Tix_Rev_Previous__c] [float] NULL,
[Season_Ticket_Spend_Previous_Season__c] [decimal] (16, 2) NULL,
[current_Season_Ticket_Spend_Previous_Season__c] [float] NULL,
[Num_games_forwarded_Previous_Season__c] [int] NULL,
[current_Num_games_forwarded_Previous_Season__c] [float] NULL,
[Num_games_posted_Previous_Season__c] [int] NULL,
[current_Num_games_posted_Previous_Season__c] [float] NULL,
[Num_games_resold_Previous_Season__c] [int] NULL,
[current_Num_games_resold_Previous_Season__c] [float] NULL,
[Num_seats_forwarded_Previous_Season__c] [int] NULL,
[current_Num_seats_forwarded_Previous_Season__c] [float] NULL,
[Num_seats_posted_Previous_Season__c] [int] NULL,
[current_Num_seats_posted_Previous_Season__c] [float] NULL,
[Num_seats_resold_Previous_Season__c] [int] NULL,
[current_Num_seats_resold_Previous_Season__c] [float] NULL,
[Num_games_bought_resale_TM_Plus_Previous__c] [int] NULL,
[current_Num_games_bought_resale_TM_Plus_Previous__c] [float] NULL,
[Num_games_received_via_Fwd_Previous__c] [int] NULL,
[current_Num_games_received_via_Fwd_Previous__c] [float] NULL,
[Num_games_bought_resale_TM_Plus_Current__c] [int] NULL,
[current_Num_games_bought_resale_TM_Plus_Current__c] [float] NULL,
[Season_Current_Season__c] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Season_Current_Season__c] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Season_Previous_Season__c] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Season_Previous_Season__c] [nvarchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Kings_App_Profile_Picture_URL__c] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[current_Kings_App_Profile_Picture_URL__c] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[diffSSB_CRMSYSTEM_SSID_Winner__c] [int] NOT NULL,
[diffSSB_CRMSYSTEM_DimCustomerIDs__c] [int] NOT NULL,
[diffSSB_CRMSYSTEM_FullArchitcs_IDs__c] [int] NOT NULL,
[diffArchtics_ID__c] [int] NOT NULL,
[diffMobilePhone] [int] NOT NULL,
[diffEmail] [int] NOT NULL,
[diffOtherPhone] [int] NOT NULL,
[diffAge__c] [int] NOT NULL,
[diffBirthday__c] [int] NOT NULL,
[diffEmail_Activity_Last_15_Days__c] [int] NOT NULL,
[diffKings_com_Web_View_Last_15_Days__c] [int] NOT NULL,
[diffMarital_Status__c] [int] NOT NULL,
[diffOccupation__c] [int] NOT NULL,
[diffPersonicX_Cluster__c] [int] NOT NULL,
[diffFax] [int] NOT NULL,
[diffNum_of_games_bought_Current_Season__c] [int] NOT NULL,
[diffNum_of_games_attended_Current_Season__c] [int] NOT NULL,
[diffAttendance_Rate_Current_Season__c] [int] NOT NULL,
[diffTotal_Kings_Tix_Rev_Previous_Season__c] [int] NOT NULL,
[diffNum_arena_events_bought_Current_Season__c] [int] NOT NULL,
[diffTotal_arena_event_Tix_Rev_Current_Season__c] [int] NOT NULL,
[diffSeason_Ticket_Spend_Current_Season__c] [int] NOT NULL,
[diffNum_of_games_forwarded_Current_Season__c] [int] NOT NULL,
[diffNum_of_games_posted_Current_Season__c] [int] NOT NULL,
[diffNum_of_games_resold_Current_Season__c] [int] NOT NULL,
[diffNum_seats_forwarded_Current_Season__c] [int] NOT NULL,
[diffNum_seats_posted_Current_Season__c] [int] NOT NULL,
[diffNum_seats_resold_Current_Season__c] [int] NOT NULL,
[diffNum_games_received_via_Fwd_Current__c] [int] NOT NULL,
[diffTot_Rev_seats_bought_resale_TM_Plus_CS__c] [int] NOT NULL,
[diffTot_rev_seats_bought_resale_TM_Plus_PS__c] [int] NOT NULL,
[diffAttendance_Rate_Previous_Season__c] [int] NOT NULL,
[diffNum_of_games_attended_Previous_Season__c] [int] NOT NULL,
[diffNum_of_games_bought_Previous_Season__c] [int] NOT NULL,
[diffNum_arena_events_bought_Previous_Season__c] [int] NOT NULL,
[diffTotal_arena_event_Tix_Rev_Previous__c] [int] NOT NULL,
[diffSeason_Ticket_Spend_Previous_Season__c] [int] NOT NULL,
[diffNum_games_forwarded_Previous_Season__c] [int] NOT NULL,
[diffNum_games_posted_Previous_Season__c] [int] NOT NULL,
[diffNum_games_resold_Previous_Season__c] [int] NOT NULL,
[diffNum_seats_forwarded_Previous_Season__c] [int] NOT NULL,
[diffNum_seats_posted_Previous_Season__c] [int] NOT NULL,
[diffNum_seats_resold_Previous_Season__c] [int] NOT NULL,
[diffNum_games_bought_resale_TM_Plus_Previous__c] [int] NOT NULL,
[diffNum_games_received_via_Fwd_Previous__c] [int] NOT NULL,
[diffNum_games_bought_resale_TM_Plus_Current__c] [int] NOT NULL,
[diffSeason_Current_Season__c] [int] NOT NULL,
[diffSeason_Previous_Season__c] [int] NOT NULL,
[diffKings_App_Profile_Picture_URL__c] [int] NOT NULL
)
GO
