CREATE TABLE [dbo].[Account_Custom]
(
[SSB_CRMSYSTEM_ACCT_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SSID_Winner] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TM_Ids] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Eloqua_IDs] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LA_Ids] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DimCustIDs] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountId] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonTicket_Years] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STH_Account] [bit] NULL,
[Salutation] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Fax] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountType] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DiscretionaryIncome] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NetWorth] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LengthOfResidence] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AdultsInHouseHold] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ChildrenFlag] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SeasonTicketSpend_Previous] [decimal] (16, 2) NULL,
[SeasonTicketSpend_Current] [decimal] (16, 2) NULL,
[RecordTypeId] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRMProcess_UpdatedDate] [datetime] NULL,
[GamesBought_Previous] [int] NULL,
[GamesBought_Current] [int] NULL,
[GamesAttended_Current] [int] NULL,
[GamesAttended_Previous] [int] NULL,
[AttendRate_Current] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AttendRate_Previous] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalTicketSpend_Current] [decimal] (16, 2) NULL,
[TotalTicketSpend_Previous] [decimal] (16, 2) NULL,
[ArenaSpend_Current] [decimal] (16, 2) NULL,
[ArenaSpend_Previous] [decimal] (16, 2) NULL,
[ArenaBought_Current] [int] NULL,
[ArenaBought_Previous] [int] NULL,
[TE_Game_NumForward_Current] [int] NULL,
[TE_Game_NumForward_Previous] [int] NULL,
[TE_Game_NumPost_Current] [int] NULL,
[TE_Game_NumPost_Previous] [int] NULL,
[TE_Game_NumSold_Current] [int] NULL,
[TE_Game_NumSold_Previous] [int] NULL,
[TE_Seat_NumForward_Current] [int] NULL,
[TE_Seat_NumForward_Previous] [int] NULL,
[TE_Seat_NumPost_Current] [int] NULL,
[TE_Seat_NumPost_Previous] [int] NULL,
[TE_Seat_NumSold_Current] [int] NULL,
[TE_Seat_NumSold_Previous] [int] NULL,
[TE_Game_NumForward_Received_Current] [int] NULL,
[TE_Game_NumForward_Received_Previous] [int] NULL,
[TE_Game_NumBought_Current] [int] NULL,
[TE_Game_NumBought_previous] [int] NULL,
[TE_Revenue_Current] [decimal] (16, 2) NULL,
[TE_Revenue_Previous] [decimal] (16, 2) NULL,
[Season_Current] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Season_Previous] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date_of_Last_Email_Open_Eloqua__c] [datetime] NULL,
[Date_of_Last_G1C_Page_Visit__c] [datetime] NULL,
[Date_of_Last_Kings_com_Visit__c] [datetime] NULL,
[Date_of_Last_Ticketing_Page_Visit__c] [datetime] NULL
)
GO
ALTER TABLE [dbo].[Account_Custom] ADD CONSTRAINT [PK_Account_Custom] PRIMARY KEY CLUSTERED  ([SSB_CRMSYSTEM_ACCT_ID])
GO
