IF NOT EXISTS (SELECT * FROM master.dbo.syslogins WHERE loginname = N'SSBCLOUD\tfrancis')
CREATE LOGIN [SSBCLOUD\tfrancis] FROM WINDOWS
GO
CREATE USER [SSBCLOUD\tfrancis] FOR LOGIN [SSBCLOUD\tfrancis] WITH DEFAULT_SCHEMA=[SSBCLOUD\tfrancis]
GO
REVOKE CONNECT TO [SSBCLOUD\tfrancis]
